# Generated by Django 5.1.1 on 2026-01-21 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_addtransaction_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addtransaction",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2026, 1, 21, 13, 57, 25, 877150)
            ),
        ),
    ]
