# Generated by Django 5.1.1 on 2026-01-21 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_addtransaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addtransaction",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
